In [1]:
import seaborn as sns 
import matplotlib.pyplot as plt
import pandas as pd






df = pd.read_excel("namcs/namcs2019_sas.xlsx")
df.isna().sum()
# df = df.dropna(axis='columns', how ='all')
df.describe()

,Unnamed: 0,VMONTH,VDAYR,AGE,AGER,AGEDAYS,SEX,PREGNANT,GESTWK,ETHUN,...,RX30V3C1,RX30V3C2,RX30V3C3,RX30V3C4,CSTRATM,CPSUM,YEAR,SETTYPE,PATWT,PHYSWT
count,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,8250.000000,...,5.000000,1.0,0.0,0.0,8.250000e+03,8250.000000,8250.0,8250.0,8.250000e+03,398.000000
mean,4124.500000,6.273455,3.696970,51.470182,3.923030,-3.270182,1.441333,-5.079515,-7.433576,-0.728485,...,239.000000,211.0,NaN,NaN,1.027476e+07,100195.877212,2019.0,1.0,1.256345e+05,844.247752
std,2381.714194,3.418679,1.385131,24.365268,1.516312,28.974158,0.496576,4.423236,4.956595,4.656875,...,121.768222,NaN,NaN,NaN,1.047204e+05,113.336393,0.0,0.0,1.837453e+05,994.897102
min,0.000000,1.000000,2.000000,0.000000,1.000000,-7.000000,1.000000,-9.000000,-9.000000,-9.000000,...,62.000000,211.0,NaN,NaN,1.011910e+07,100001.000000,2019.0,1.0,7.064007e+03,65.663900
25%,2062.250000,3.000000,2.000000,34.000000,3.000000,-7.000000,1.000000,-9.000000,-9.000000,1.000000,...,173.000000,211.0,NaN,NaN,1.021910e+07,100098.000000,2019.0,1.0,2.516130e+04,191.298350
50%,4124.500000,6.000000,3.000000,57.000000,4.000000,-7.000000,1.000000,-7.000000,-9.000000,2.000000,...,290.000000,211.0,NaN,NaN,1.031910e+07,100194.000000,2019.0,1.0,6.629652e+04,466.842490
75%,6186.750000,9.000000,5.000000,71.000000,5.000000,-7.000000,2.000000,2.000000,-7.000000,2.000000,...,299.000000,211.0,NaN,NaN,1.031911e+07,100293.000000,2019.0,1.0,1.486985e+05,1168.695635
max,8249.000000,12.000000,7.000000,94.000000,6.000000,364.000000,2.000000,2.000000,40.000000,2.000000,...,371.000000,211.0,NaN,NaN,1.041912e+07,100398.000000,2019.0,1.0,1.120997e+06,4901.609570

In [4]:
df.shape

(8250, 864)